rules:
    default_issue_labels:
      description: Add default labels to newly created issues
      events: [issues1]
      condition:
        - action == "opened"
      action:
        label: [unconfirmed]
