rules:
    default_issue_labels:
      description: Add default labels to newly created issues
      events: [issues]
      condition:
        - action == "opened"
        - issue.body matches "\|\s*Bug fix\?\s*\|\s*(yes)(?!\/no)\s*"
      action:
        label: [unconfirmed, bug]
#        comment: > 
#            Hello @{{ user.login }}! Thanks for this issue in {{ repository.full_name }}!
#            
#            And test multi line comments                   
