rules:
    default_issue_labels:
      description: Add default labels to newly created issues
      events: [issues]
      condition:
        - action == "opened"
      action:
        label: [unconfirmed]
        comment: > 
            Hello @{{ user.login }}! Thanks for this issue in {{ repository.full_name }}!
            
            And test multi line comments                   
