rules:
    default_issue_labels:
      description: Add default labels to newly created issues
      events: [issues]
      condition:
        - action == "opened"
      action:
        label: [unconfirmed]
        comment: Hello @{{ user.name }}! Thanks for this issue!
